access_key = ""
secret_key = ""
region = "ap-northeast-1"
zone = "ap-northeast-1a"
database_user_name = "tf_tester"
database_user_password = "Tikin115"
database_name = "mysql_begginer"
database_character = "utf8"